spring:
  main:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sales
      username: root
      password: root
  jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 1290